name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - .vscode/**
  pull_request:
    paths-ignore:
      - .github/**
      - .vscode/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Main Job
    uses: ./.github/workflows/nx-cloud-main.yml
    secrets: inherit
    with:
      number-of-agents: 3
      python-version: '3.11'
      init-commands: |
        python -m pip install --upgrade pip
        pip install pdm
      parallel-commands: |
        pnpm exec nx-cloud record -- pnpm exec nx format:check
      parallel-commands-on-agents: |
        pnpm exec nx affected --target=lint --parallel=3
        pnpm exec nx affected --target=test --parallel=3 --ci --code-coverage
        pnpm exec nx affected --target=build --parallel=3
        pnpm exec nx affected --target=e2e --parallel=3

  agents:
    name: Agents
    uses: ./.github/workflows/nx-cloud-agents.yml
    secrets: inherit
    with:
      number-of-agents: 3
      python-version: '3.11'
      init-commands: |
        python -m pip install --upgrade pip
        pip install pdm
